version: '3.8'
name: olive-turtle
services:
    mqttserver:
        image: "eclipse-mosquitto:2.0.15"
        container_name: mqttserver
        restart: unless-stopped
        ports:
            - "1883:1883"
        networks:
            - iot_net
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
            - $MQTT_ROOT_FOLDER/config:/mosquitto/config
            - $MQTT_ROOT_FOLDER/credentials.txt:/mosquitto/credentials.txt
        environment:
            - TZ=Europe/Rome
    influxdb:
        image: "influxdb:2.7.1"
        container_name: influxdb
        restart: unless-stopped
        ports:
            - "8086:8086"
        networks:
            - iot_net
        volumes:
            - influxdb_data:/var/lib/influxdb2
            - influxdb_config:/etc/influxdb2
            - influxdb_backup:/var/lib/backup
        environment:
            - TZ=Europe/Rome
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=$INFLUXDB_USERNAME
            - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_PASSWORD
            - DOCKER_INFLUXDB_INIT_ORG=$INFLUXDB_ORG
            - DOCKER_INFLUXDB_INIT_BUCKET=$INFLUXDB_BUCKET
        healthcheck:
            test: ["CMD", "influx", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
    telegraf:
        image: "telegraf:1.26.2"
        container_name: telegraf
        restart: unless-stopped
        depends_on:
            - mqttserver
            - influxdb
        networks:
            - iot_net
        volumes:
            - $TELEGRAF_ROOT_FOLDER/telegraf.conf:/etc/telegraf/telegraf.conf
        environment:
            - TZ=Europe/Rome
            - INFLUXDB_V2_URL=$INFLUXDB_HOST
            - INFLUXDB_V2_TOKEN=$TELEGRAF_INFLUXDB_TOKEN
            - INFLUXDB_V2_ORG=$INFLUXDB_ORG
            - INFLUXDB_V2_BUCKET=$INFLUXDB_BUCKET
            - MQTT_CLIENT_ID=telegraf
            - MQTT_ADDRESS=$MQTT_HOST
            - MQTT_USER=$TELEGRAF_MQTT_USERNAME
            - MQTT_PASSWORD=$TELEGRAF_MQTT_PASSWORD

volumes:
    mosquitto_data:
    mosquitto_log:
    mosquitto_config:
    influxdb_data:
    influxdb_config:
    influxdb_backup:

networks:
    iot_net: