version: '3.8'
name: olive-turtle
services:
    mqtt-init:
        image: "alpine:latest"
        volumes:
            - mosquitto_config:/mosquitto/config
        command:
            - /bin/sh
            - -c
            - |
                [ -f /mosquitto/config/mosquitto.conf ] || echo "Creating config at /mosquitto/config/mosquitto.conf" && echo -e "$MQTT_CONFIG" > /mosquitto/config/mosquitto.conf
               # [ -f /mosquitto/config/credentials.txt ] || echo "Creating config at /mosquitto/config/credentials.txt" && echo -e "$MQTT_CREDENTIALS" > /mosquitto/config/credentials.txt
    mqttserver:
        image: "eclipse-mosquitto:2.0.15"
        container_name: mqttserver
        restart: unless-stopped
        ports:
            - "1883:1883"
        networks:
            - iot_net
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
            - mosquitto_config:/mosquitto/config
        environment:
            - TZ=Europe/Rome
    influxdb:
        image: "influxdb:2.7.1"
        container_name: influxdb
        restart: unless-stopped
        ports:
            - "8086:8086"
        networks:
            - iot_net
        volumes:
            - influxdb_data:/var/lib/influxdb2
            - influxdb_config:/etc/influxdb2
            - influxdb_backup:/var/lib/backup
        environment:
            - TZ=Europe/Rome
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=$INFLUXDB_USERNAME
            - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_PASSWORD
            - DOCKER_INFLUXDB_INIT_ORG=$INFLUXDB_ORG
            - DOCKER_INFLUXDB_INIT_BUCKET=$INFLUXDB_BUCKET
        healthcheck:
            test: ["CMD", "influx", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
    mqtt-agent:
        image: "aleben/green-ferret_mqtt-agent:1.0"
        depends_on:
            - mqttserver
            - influxdb
        container_name: mqtt-agent
        restart: unless-stopped
        networks:
            - iot_net
        environment:
            - MQTT_HOST=$MQTT_AGENT_HOST
            - MQTT_PORT=$MQTT_AGENT_PORT
            - MQTT_USERNAME=$MQTT_AGENT_USERNAME
            - MQTT_PASSWORD=$MQTT_AGENT_PASSWORD
            - MQTT_CLIENT_ID=$MQTT_AGENT_CLIENT_ID
            - INFLUXDB_HOST=$INFLUXDB_HOST
            - INFLUXDB_PORT=$INFLUXDB_PORT
            - INFLUXDB_ORG=$INFLUXDB_ORG
            - INFLUXDB_BUCKET=$INFLUXDB_BUCKET
            - INFLUXDB_TOKEN=$MQTT_AGENT_INFLUXDB_TOKEN

volumes:
    mosquitto_data:
    mosquitto_log:
    mosquitto_config:
    influxdb_data:
    influxdb_config:
    influxdb_backup:

networks:
    iot_net: